force-app/main/default/objects/Bundle__c/Bundle__c.object-meta.xml
<CustomObject>
    <label>Merchandise Bundle</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchandise Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <summarizedField>Bundle_Item__c.Qty__c</summarizedField>
    <summaryForeignKey>Bundle_Item__c.Bundle__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bundle_Item__c/Bundle_Item__c.object-meta.xml
<CustomObject>
    <label>Bundle Item</label>
    <nameField>
        <displayFormat>MI-{0000000}</displayFormat>
        <label>Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Item__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <label>Bundle</label>
    <referenceTo>Bundle__c</referenceTo>
    <relationshipLabel>Bundles</relationshipLabel>
    <relationshipName>Bundles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Item__c/fields/Merchandise__c.field-meta.xml
<CustomField>
    <fullName>Merchandise__c</fullName>
    <label>Merchandise</label>
    <referenceTo>Merchandise__c</referenceTo>
    <relationshipLabel>Bundle Items</relationshipLabel>
    <relationshipName>Bundle_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bundle_Item__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Merchandise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchandise__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Womens</fullName>
            </value>
            <value>
                <fullName>Mens</fullName>
            </value>
            <value>
                <fullName>Kids</fullName>
            </value>
            <value>
                <fullName>Gear</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BundleController.cls
global with sharing class BundleController {
    @AuraEnabled(cacheable=true)
    public static List<Bundle_Item__c> getBundleItems(Id bundleId) {
        return [
            SELECT
                Id,
                Merchandise__r.Name,
                Merchandise__r.Title__c,
                Merchandise__r.Price__c,
                Merchandise__r.Category__c,
                Merchandise__r.Picture_URL__c,
                Qty__c
            FROM Bundle_Item__c
            WHERE Bundle__c = :bundleId
            WITH SECURITY_ENFORCED
        ];
    }
}