force-app/main/default/objects/Harvest_Field__c/Harvest_Field__c.object-meta.xml
<CustomObject>
    <label>Harvest Field</label>
    <nameField>
        <label>Harvest Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Harvest Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Harvest_Field__c/fields/Crop__c.field-meta.xml
<CustomField>
    <fullName>Crop__c</fullName>
    <label>Crop</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aloe</fullName>
            </value>
            <value>
                <fullName>Eggplant</fullName>
            </value>
            <value>
                <fullName>Kale</fullName>
            </value>
            <value>
                <fullName>Pumpkin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Harvest_Field__c/fields/Irrigation__c.field-meta.xml
<CustomField>
    <fullName>Irrigation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Irrigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Harvest_Field__c/fields/Map_Id__c.field-meta.xml
<CustomField>
    <fullName>Map_Id__c</fullName>
    <label>Map Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Harvest_Field__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Harvest_Field__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alert</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Harvest_Field__c/fields/Yield__c.field-meta.xml
<CustomField>
    <fullName>Yield__c</fullName>
    <label>Yield</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HarvestFieldController.cls
global with sharing class HarvestFieldController {
    @AuraEnabled(cacheable=true)
    public static List<Harvest_Field__c> getHarvestFields() {
        return [
            SELECT
                Id,
                Name,
                Crop__c,
                Size__c,
                Status__c,
                Map_Id__c,
                Yield__c,
                Irrigation__c,
                Picture_URL__c
            FROM Harvest_Field__c
            WITH SECURITY_ENFORCED
            LIMIT 20
        ];
    }
}